#!/usr/bin/env bash
set -xe

case $# in
    0)
        printf 'Usage: %q <yuki|ibus|qwerty>' "$0"
        exit 1
        ;;
    1)
        profile="$1"
        ;;
esac

declare -A profiles=(
    [yuki]="[('xkb', 'us_yuki+colemak_dh'), ('xkb', 'ru_yuki+rulemak_dh')]"
    [ibus]="[('ibus', 'anthy'), ('ibus', 'table:ipa-x-sampa')]"
    [qwerty]="[('xkb', 'us'), ('xkb', 'ru')]"
)

# Reset on unknown profile name
[[ -z "${profiles[$profile]}" ]] && profile=yuki

gsettings set org.gnome.desktop.input-sources sources "${profiles[$profile]}"
# openrgb --noautoconnect --profile "$profile"

