#!/bin/bash

win=$1
sid=$2

LOCK_BASE=`realpath ~/.cache/eww-lock`
close() {
    eww close $win
    rm -f "$LOCK_BASE.$win-$sid"
}

close_all() {
    windows="system music_win calendar network activities wireless"
    eww close $windows
    rm -f $LOCK_BASE.*
}

open() {
    echo > "$LOCK_BASE.$win-$sid"
    eww open $win --screen $sid
}

if [[ -f "$LOCK_BASE.$win-$sid" ]]; then
    close
else
    close_all
    open
fi
