#!/bin/bash

LOCK_BASE=`realpath ~/.cache/eww-lock`
close() {
    eww close $1
    rm -f "$LOCK_BASE.$1"
}

close_all() {
    for wnd in system music_win calendar network activities wireless; do
        close $wnd
    done
}

open() {
    echo > "$LOCK_BASE.$1"
    eww open $1 --screen 0
}

toggle() {
    if [[ -f "$LOCK_BASE.$1" ]]; then
        close $1
    else
        close_all
        open $1
    fi
}

toggle "$1"
