#!/bin/bash

[[ -n "$1" ]] || exit 1

repeat() {
    answer=$(wpctl get-volume $1)

    <<<$answer sed -uE -e 's/$/}/' -e 's/Volume: 0?([0-9]*)\.([0-9]{2})/{"vol":\1\2/' -e 's/ \[MUTED\]/,"muted":true/' -e 's/:0/:/'

    if [[ "$1" == *SINK* ]]; then
        icon=audio-volume
        name=Output
    else
        icon=microphone-sensitivity
        name=Input
    fi

    if [[ "$answer" == *MUTED* ]]; then
        icon=$icon-muted
        name="$name, muted"
    else
        icon=$icon-high
    fi

    level=${answer/" [MUTED]"//}
    level=${level/"Volume: "/}
    level=${level/./}

    dunstify \
        -a wireplumber-watcher \
        -u low \
        -i $icon \
        -h string:x-dunst-stack-tag:volume-$1 \
        -h int:value:$level \
        -t 1000 \
        "$name"
}

id=@DEFAULT_`echo $1 | tr a-z A-Z`@

repeat $id
while read -r _; do
    repeat $id
done < <(< <(pactl -fjson subscribe) exec jq --unbuffered -rc "select(.event==\"change\") | select(.on==\"$1\") | .index")
