#!/bin/bash

[[ -n "$1" ]] || exit 1

into_json() {
    sed -uE -e 's/$/}/' -e 's/Volume: 0?([0-9]*)\.([0-9]{2})/{"vol":\1\2/' -e 's/ \[MUTED\]/,"muted":true/' -e 's/:0/:/'
}

repeat() {
    wpctl get-volume $1 | into_json
}

id=@DEFAULT_`echo $1 | tr a-z A-Z`@

repeat $id
pactl -fjson subscribe | jq --unbuffered -rc "select(.event==\"change\") | select(.on==\"$1\") | .index" | while read -r id; do
    repeat $id
done
