# vim: ft=bash

for file in ~/.config/environment.d/*.conf; do
    source <(sed 's|^|export |' "$file")
done

export XDG_RUNTIME_DIR=/run/user/$(id -u)

[[ $- != *i* ]] && return

for file in ~/.config/bash/bashrc.d/*.sh; do
    source "$file"
done

