#!/bin/sh
killall swayidle
exec swayidle -w \
    timeout 270 "~/.config/sway/lock" \
    timeout 300 "swaymsg 'output * power off'" resume "swaymsg 'output * power on'" \
    before-sleep "~/.config/sway/lock" \
    before-sleep "swaymsg 'output * power off'" \
    after-resume "swaymsg 'output * power on'"
