#!/bin/sh
set -exuo pipefail
if swaymsg -t get_inputs | busybox grep Colemak >/dev/null; then
    swaymsg 'input type:keyboard xkb_variant "basic,winkeys"'
else
    swaymsg 'input type:keyboard xkb_variant "colemak_dh_yuki,rulemak_dh_yuki"'
fi
